// lib/language.ts
export const languages = {
  en: { code: 'en', name: 'English', dir: 'ltr' },
  ar: { code: 'ar', name: 'العربية', dir: 'rtl' },
  bn: { code: 'bn', name: 'বাংলা', dir: 'ltr' },
  hi: { code: 'hi', name: 'हिन्दी', dir: 'ltr' },
};

export type LangCode = keyof typeof languages;

export const texts: Record<LangCode, Record<string, string>> = {
  en: {
    searchPlaceholder: 'Search by name or number...',
    navSearch: 'Search',
    home: 'Home',
    profile: 'Profile',
    create: 'Create',
    dashboard: 'Dashboard',
    map: 'Map',
    bid: 'Bid',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    settings: 'Settings',
    featured: 'Featured Workers',
    categories: 'Categories',
    allWorkers: 'All Workers',
    viewAll: 'View All',
    online: 'Online',
    offline: 'Offline',
    salary: 'Salary',
    experience: 'Experience',
    contact: 'Contact',
    whatsapp: 'WhatsApp',
    call: 'Call',
    jobOffer: 'Job Offer',
    createProfile: 'Create Profile',
    postJob: 'Post a Job',
    selectCountry: 'Select Country',
    selectCity: 'Select City',
    selectArea: 'Select Area',
    views: 'Views',
    contacts: 'Contacts',
    offers: 'Job Offers',
    hired: 'Hired',
    labor: 'Labor',
    employer: 'Employer',
    back: 'Back',
    sendOTP: 'Send OTP',
    noAccount: "Don't have account?",
    biodata: 'Biodata',
    skills: 'Skills',
    reviews: 'Reviews',
    workPhotos: 'Work Photos',
    about: 'About',
    popularSearches: 'Popular Searches',
    allDistance: 'All Distance',
    viewProfile: 'View Profile',
    noResults: 'No results found',
    noSkills: 'No skills listed',
    share: 'Share',
    report: 'Report',
    save: 'Save',
    noReviews: 'No reviews yet',
    noActivity: 'No recent activity',
    liveActivity: 'Live Activity',
    jobPosts: 'Job Posts',
    savedWorkers: 'Saved Workers',
    findLabor: 'Find Labor',
    hiring: 'HIRING',
    response: 'Response',
    rating: 'Rating',
    month: 'month',
    notSpecified: 'Not specified',
    similarWorkers: 'Similar Workers',
    sendJobOffer: 'Send Job Offer',
    bookWorker: 'Book This Worker',
    jobTitle: 'Job Title *',
    jobDescription: 'Job Description *',
    category: 'Category',
    offerAmount: 'Offer Amount (QAR) *',
    paymentType: 'Payment Type',
    fixedPrice: 'Fixed Price',
    hourlyRate: 'Hourly Rate',
    dailyRate: 'Daily Rate',
    paymentMethod: 'Payment Method',
    cash: 'Cash',
    bankTransfer: 'Bank Transfer',
    mobileBanking: 'Mobile Banking',
    startDate: 'Start Date *',
    startTime: 'Start Time *',
    duration: 'Duration (Days) *',
    location: 'Job Location *',
    specialInstructions: 'Special Instructions',
    yourPhone: 'Your Phone *',
    sendRequest: 'Send Booking Request',
    totalAmount: 'Total Amount',
    qar: 'QAR',
    perHour: 'per hour',
    perDay: 'per day',
    bookingRequests: 'Booking Requests',
    noRequests: 'No pending requests',
    accept: 'Accept',
    reject: 'Reject',
    negotiate: 'Negotiate',
    from: 'From',
    eta: 'ETA',
    distance: 'Distance',
    bookingStatus: 'Booking Status',
    pending: 'Pending',
    accepted: 'Accepted',
    completed: 'Completed',
    workerOnWay: 'Worker is coming to you',
    workerArrived: 'Worker arrived',
    workInProgress: 'Work in progress',
    finishWork: 'Finish Work',
    markComplete: 'Mark as Complete',
    nearbyWorkers: 'Nearby Workers',
    kmAway: 'km away',
    mins: 'mins',
    hire: 'Hire',
    noNearbyWorkers: 'No workers available nearby',
    youOffered: 'You offered',
    workerCountered: 'Worker countered',
    proposeNew: 'Propose New',
    bookingSuccess: 'Booking request sent successfully!',
    bookingAccepted: 'Booking accepted! Worker is on the way.',
    bookingRejected: 'Booking rejected.',
    bookingCompleted: 'Work completed! Please rate the worker.',
    errorOccurred: 'An error occurred. Please try again.',
    posting: 'Posting...',
    submitting: 'Submitting...',
    required: 'Please fill all required fields',
    bid_amount: 'Please enter bid amount',
    posted: 'Job Posted!',
    bid_success: 'Bid Placed Successfully!',
    lowest: 'Lowest Bid',
    close: 'Close',
    be_first: 'Be the first to bid!',
    no_bids_yet: 'No bids yet',
    login_required: 'Please login to continue',
  },
  bn: {
    searchPlaceholder: 'নাম বা নাম্বার দিয়ে খুঁজুন...',
    navSearch: 'সার্চ',
    home: 'হোম',
    profile: 'প্রোফাইল',
    create: 'তৈরি',
    dashboard: 'ড্যাশবোর্ড',
    map: 'ম্যাপ',
    bid: 'বিড',
    login: 'লগইন',
    register: 'রেজিস্টার',
    logout: 'লগআউট',
    settings: 'সেটিংস',
    featured: 'ফিচার্ড কর্মী',
    categories: 'ক্যাটাগরি',
    allWorkers: 'সব কর্মী',
    viewAll: 'সব দেখুন',
    online: 'অনলাইন',
    offline: 'অফলাইন',
    salary: 'বেতন',
    experience: 'অভিজ্ঞতা',
    contact: 'যোগাযোগ',
    whatsapp: 'হোয়াটসঅ্যাপ',
    call: 'কল',
    jobOffer: 'জব অফার',
    createProfile: 'প্রোফাইল তৈরি',
    postJob: 'জব পোস্ট',
    selectCountry: 'দেশ বাছুন',
    selectCity: 'শহর বাছুন',
    selectArea: 'এরিয়া বাছুন',
    views: 'ভিউ',
    contacts: 'যোগাযোগ',
    offers: 'জব অফার',
    hired: 'নিয়োগ',
    labor: 'শ্রমিক',
    employer: 'নিয়োগকর্তা',
    back: 'ফিরুন',
    sendOTP: 'OTP পাঠান',
    noAccount: 'অ্যাকাউন্ট নেই?',
    biodata: 'বায়োডাটা',
    skills: 'দক্ষতা',
    reviews: 'রিভিউ',
    workPhotos: 'কাজের ছবি',
    about: 'সম্পর্কে',
    popularSearches: 'জনপ্রিয় সার্চ',
    allDistance: 'সব দূরত্ব',
    viewProfile: 'প্রোফাইল দেখুন',
    noResults: 'কোনো ফলাফল নেই',
    noSkills: 'কোনো দক্ষতা নেই',
    share: 'শেয়ার',
    report: 'রিপোর্ট',
    save: 'সেভ',
    noReviews: 'এখনো কোনো রিভিউ নেই',
    noActivity: 'কোনো সাম্প্রতিক কার্যকলাপ নেই',
    liveActivity: 'লাইভ অ্যাক্টিভিটি',
    jobPosts: 'জব পোস্ট',
    savedWorkers: 'সেভ করা কর্মী',
    findLabor: 'শ্রমিক খুঁজুন',
    hiring: 'নিয়োগ',
    response: 'সাড়া',
    rating: 'রেটিং',
    month: 'মাস',
    notSpecified: 'নির্ধারিত নয়',
    similarWorkers: 'অনুরূপ কর্মী',
    sendJobOffer: 'জব অফার পাঠান',
    bookWorker: 'শ্রমিক বুক করুন',
    jobTitle: 'কাজের শিরোনাম *',
    jobDescription: 'কাজের বিবরণ *',
    category: 'ক্যাটাগরি',
    offerAmount: 'অফার মূল্য (রিয়াল) *',
    paymentType: 'পেমেন্ট টাইপ',
    fixedPrice: 'নির্দিষ্ট মূল্য',
    hourlyRate: 'ঘন্টা হিসাবে',
    dailyRate: 'দিন হিসাবে',
    paymentMethod: 'পেমেন্ট পদ্ধতি',
    cash: 'নগদ',
    bankTransfer: 'ব্যাংক ট্রান্সফার',
    mobileBanking: 'মোবাইল ব্যাংকিং',
    startDate: 'শুরুর তারিখ *',
    startTime: 'শুরুর সময় *',
    duration: 'দিন সংখ্যা *',
    location: 'কাজের অবস্থান *',
    specialInstructions: 'বিশেষ নির্দেশনা',
    yourPhone: 'আপনার ফোন *',
    sendRequest: 'বুকিং রিকোয়েস্ট পাঠান',
    totalAmount: 'মোট মূল্য',
    qar: 'রিয়াল',
    perHour: 'ঘন্টা প্রতি',
    perDay: 'দিন প্রতি',
    bookingRequests: 'বুকিং রিকোয়েস্ট',
    noRequests: 'কোনো রিকোয়েস্ট নেই',
    accept: 'গ্রহণ করুন',
    reject: 'বাতিল করুন',
    negotiate: 'দরদাম করুন',
    from: 'থেকে',
    eta: 'পৌঁছাতে সময়',
    distance: 'দূরত্ব',
    bookingStatus: 'বুকিং স্ট্যাটাস',
    pending: 'অপেক্ষমান',
    accepted: 'গৃহীত',
    completed: 'সম্পন্ন',
    workerOnWay: 'শ্রমিক আপনার দিকে আসছে',
    workerArrived: 'শ্রমিক পৌঁছে গেছেন',
    workInProgress: 'কাজ চলছে',
    finishWork: 'কাজ শেষ করুন',
    markComplete: 'সম্পন্ন করুন',
    nearbyWorkers: 'কাছাকাছি শ্রমিক',
    kmAway: 'কিমি দূরে',
    mins: 'মিনিট',
    hire: 'নিয়োগ',
    noNearbyWorkers: 'কাছাকাছি কোনো শ্রমিক নেই',
    youOffered: 'আপনি অফার করেছেন',
    workerCountered: 'শ্রমিক কাউন্টার দিয়েছেন',
    proposeNew: 'নতুন প্রস্তাব দিন',
    bookingSuccess: 'বুকিং রিকোয়েস্ট সফলভাবে পাঠানো হয়েছে!',
    bookingAccepted: 'বুকিং গৃহীত হয়েছে! শ্রমিক আসছে।',
    bookingRejected: 'বুকিং বাতিল করা হয়েছে।',
    bookingCompleted: 'কাজ সম্পন্ন হয়েছে! শ্রমিককে রেটিং দিন।',
    errorOccurred: 'একটি সমস্যা হয়েছে। আবার চেষ্টা করুন।',
    posting: 'পোস্ট হচ্ছে...',
    submitting: 'জমা হচ্ছে...',
    required: 'সব প্রয়োজনীয় তথ্য পূরণ করুন',
    bid_amount: 'বিড মূল্য দিন',
    posted: 'জব পোস্ট হয়েছে!',
    bid_success: 'বিড সফলভাবে প্লেস হয়েছে!',
    lowest: 'সর্বনিম্ন বিড',
    close: 'বন্ধ',
    be_first: 'প্রথম বিড করুন!',
    no_bids_yet: 'কোনো বিড নেই',
    login_required: 'চালিয়ে যেতে লগইন করুন',
  },
  ar: {
    searchPlaceholder: 'ابحث بالاسم أو الرقم...',
    navSearch: 'بحث',
    home: 'الرئيسية',
    profile: 'الملف',
    create: 'إنشاء',
    dashboard: 'لوحة التحكم',
    map: 'خريطة',
    bid: 'مزايدة',
    login: 'تسجيل الدخول',
    register: 'تسجيل',
    logout: 'تسجيل الخروج',
    settings: 'الإعدادات',
    featured: 'عمال مميزون',
    categories: 'الفئات',
    allWorkers: 'جميع العمال',
    viewAll: 'عرض الكل',
    online: 'متصل',
    offline: 'غير متصل',
    salary: 'الراتب',
    experience: 'الخبرة',
    contact: 'اتصال',
    whatsapp: 'واتساب',
    call: 'اتصل الآن',
    jobOffer: 'عرض عمل',
    createProfile: 'إنشاء ملف',
    postJob: 'نشر وظيفة',
    selectCountry: 'اختر البلد',
    selectCity: 'اختر المدينة',
    selectArea: 'اختر المنطقة',
    views: 'مشاهدات',
    contacts: 'جهات اتصال',
    offers: 'عروض عمل',
    hired: 'موظف',
    labor: 'عامل',
    employer: 'صاحب عمل',
    back: 'رجوع',
    sendOTP: 'إرسال OTP',
    noAccount: 'ليس لديك حساب؟',
    biodata: 'بيانات',
    skills: 'مهارات',
    reviews: 'تقييمات',
    workPhotos: 'صور العمل',
    about: 'حول',
    popularSearches: 'البحوث الشائعة',
    allDistance: 'كل المسافات',
    viewProfile: 'عرض الملف',
    noResults: 'لا توجد نتائج',
    noSkills: 'لا توجد مهارات',
    share: 'مشاركة',
    report: 'إبلاغ',
    save: 'حفظ',
    noReviews: 'لا توجد تقييمات',
    noActivity: 'لا يوجد نشاط حديث',
    liveActivity: 'نشاط مباشر',
    jobPosts: 'الوظائف',
    savedWorkers: 'العمال المحفوظين',
    findLabor: 'البحث عن عمال',
    hiring: 'توظيف',
    response: 'رد',
    rating: 'تقييم',
    month: 'شهر',
    notSpecified: 'غير محدد',
    similarWorkers: 'عمال مشابهين',
    sendJobOffer: 'إرسال عرض عمل',
    bookWorker: 'احجز هذا العامل',
    jobTitle: 'عنوان الوظيفة *',
    jobDescription: 'وصف الوظيفة *',
    category: 'الفئة',
    offerAmount: 'المبلغ المعروض (ريال) *',
    paymentType: 'نوع الدفع',
    fixedPrice: 'سعر ثابت',
    hourlyRate: 'بالساعة',
    dailyRate: 'باليوم',
    paymentMethod: 'طريقة الدفع',
    cash: 'نقدًا',
    bankTransfer: 'تحويل بنكي',
    mobileBanking: 'خدمات مصرفية متنقلة',
    startDate: 'تاريخ البدء *',
    startTime: 'وقت البدء *',
    duration: 'المدة (أيام) *',
    location: 'موقع العمل *',
    specialInstructions: 'تعليمات خاصة',
    yourPhone: 'هاتفك *',
    sendRequest: 'إرسال طلب الحجز',
    totalAmount: 'المبلغ الإجمالي',
    qar: 'ريال',
    perHour: 'في الساعة',
    perDay: 'في اليوم',
    bookingRequests: 'طلبات الحجز',
    noRequests: 'لا توجد طلبات معلقة',
    accept: 'قبول',
    reject: 'رفض',
    negotiate: 'تفاوض',
    from: 'من',
    eta: 'الوقت المتوقع',
    distance: 'المسافة',
    bookingStatus: 'حالة الحجز',
    pending: 'قيد الانتظار',
    accepted: 'مقبول',
    completed: 'مكتمل',
    workerOnWay: 'العامل في طريقه إليك',
    workerArrived: 'وصل العامل',
    workInProgress: 'العمل جار',
    finishWork: 'إنهاء العمل',
    markComplete: 'وضع كمكتمل',
    nearbyWorkers: 'عمال قريب',
    kmAway: 'كم',
    mins: 'دقيقة',
    hire: 'استأجر',
    noNearbyWorkers: 'لا يوجد عمال قريب',
    youOffered: 'عرضت',
    workerCountered: 'العامل عرض',
    proposeNew: 'اقترح جديد',
    bookingSuccess: 'تم إرسال طلب الحجز بنجاح!',
    bookingAccepted: 'تم قبول الحجز! العامل في الطريق.',
    bookingRejected: 'تم رفض الحجز.',
    bookingCompleted: 'اكتمل العمل! يرجى تقييم العامل.',
    errorOccurred: 'حدث خطأ. يرجى المحاولة مرة أخرى.',
    posting: 'جاري النشر...',
    submitting: 'جاري الإرسال...',
    required: 'يرجى ملء جميع الحقول المطلوبة',
    bid_amount: 'أدخل مبلغ العرض',
    posted: 'تم نشر الوظيفة!',
    bid_success: 'تم تقديم العرض بنجاح!',
    lowest: 'أقل عرض',
    close: 'إغلاق',
    be_first: 'كن الأول!',
    no_bids_yet: 'لا توجد عروض بعد',
    login_required: 'يرجى تسجيل الدخول للمتابعة',
  },
  hi: {
    searchPlaceholder: 'नाम या नंबर से खोजें...',
    navSearch: 'खोज',
    home: 'होम',
    profile: 'प्रोफाइल',
    create: 'बनाएं',
    dashboard: 'डैशबोर्ड',
    map: 'मैप',
    bid: 'बिड',
    login: 'लॉगिन',
    register: 'रजिस्टर',
    logout: 'लॉगआउट',
    settings: 'सेटिंग्स',
    featured: 'फीचर्ड वर्कर',
    categories: 'श्रेणियां',
    allWorkers: 'सभी कर्मचारी',
    viewAll: 'सभी देखें',
    online: 'ऑनलाइन',
    offline: 'ऑफलाइन',
    salary: 'वेतन',
    experience: 'अनुभव',
    contact: 'संपर्क',
    whatsapp: 'व्हाट्सएप',
    call: 'कॉल',
    jobOffer: 'जॉब ऑफर',
    createProfile: 'प्रोफाइल बनाएं',
    postJob: 'जॉब पोस्ट करें',
    selectCountry: 'देश चुनें',
    selectCity: 'शहर चुनें',
    selectArea: 'क्षेत्र चुनें',
    views: 'व्यूज',
    contacts: 'संपर्क',
    offers: 'जॉब ऑफर',
    hired: 'नियुक्त',
    labor: 'श्रमिक',
    employer: 'नियोक्ता',
    back: 'वापस',
    sendOTP: 'OTP भेजें',
    noAccount: 'खाता नहीं है?',
    biodata: 'बायोडाटा',
    skills: 'कौशल',
    reviews: 'समीक्षा',
    workPhotos: 'काम की तस्वीरें',
    about: 'बारे में',
    popularSearches: 'लोकप्रिय खोज',
    allDistance: 'सभी दूरी',
    viewProfile: 'प्रोफाइल देखें',
    noResults: 'कोई परिणाम नहीं',
    noSkills: 'कोई कौशल नहीं',
    share: 'शेयर',
    report: 'रिपोर्ट',
    save: 'सहेजें',
    noReviews: 'अभी तक कोई समीक्षा नहीं',
    noActivity: 'कोई हालिया गतिविधि नहीं',
    liveActivity: 'लाइव गतिविधि',
    jobPosts: 'जॉब पोस्ट',
    savedWorkers: 'सहेजे गए श्रमिक',
    findLabor: 'श्रमिक खोजें',
    hiring: 'नियुक्ति',
    response: 'प्रतिक्रिया',
    rating: 'रेटिंग',
    month: 'महीना',
    notSpecified: 'निर्दिष्ट नहीं',
    similarWorkers: 'समान श्रमिक',
    sendJobOffer: 'जॉब ऑफर भेजें',
    bookWorker: 'इस कर्मचारी को बुक करें',
    jobTitle: 'नौकरी का शीर्षक *',
    jobDescription: 'नौकरी का विवरण *',
    category: 'श्रेणी',
    offerAmount: 'प्रस्ताव राशि (रियाल) *',
    paymentType: 'भुगतान प्रकार',
    fixedPrice: 'निश्चित मूल्य',
    hourlyRate: 'प्रति घंटा',
    dailyRate: 'प्रति दिन',
    paymentMethod: 'भुगतान विधि',
    cash: 'नकद',
    bankTransfer: 'बैंक ट्रांसफर',
    mobileBanking: 'मोबाइल बैंकिंग',
    startDate: 'प्रारंभ तिथि *',
    startTime: 'प्रारंभ समय *',
    duration: 'अवधि (दिन) *',
    location: 'कार्य स्थान *',
    specialInstructions: 'विशेष निर्देश',
    yourPhone: 'आपका फोन *',
    sendRequest: 'बुकिंग अनुरोध भेजें',
    totalAmount: 'कुल राशि',
    qar: 'रियाल',
    perHour: 'प्रति घंटा',
    perDay: 'प्रति दिन',
    bookingRequests: 'बुकिंग अनुरोध',
    noRequests: 'कोई अनुरोध नहीं',
    accept: 'स्वीकार करें',
    reject: 'अस्वीकार करें',
    negotiate: 'बातचीत करें',
    from: 'से',
    eta: 'अनुमानित समय',
    distance: 'दूरी',
    bookingStatus: 'बुकिंग स्थिति',
    pending: 'लंबित',
    accepted: 'स्वीकृत',
    completed: 'पूर्ण',
    workerOnWay: 'श्रमिक आपके पास आ रहा है',
    workerArrived: 'श्रमिक पहुंच गया',
    workInProgress: 'कार्य प्रगति पर',
    finishWork: 'कार्य समाप्त करें',
    markComplete: 'पूर्ण चिह्नित करें',
    nearbyWorkers: 'पास के श्रमिक',
    kmAway: 'किमी दूर',
    mins: 'मिनट',
    hire: 'किराया',
    noNearbyWorkers: 'पास में कोई श्रमिक नहीं',
    youOffered: 'आपने प्रस्ताव दिया',
    workerCountered: 'श्रमिक ने जवाब दिया',
    proposeNew: 'नया प्रस्ताव दें',
    bookingSuccess: 'बुकिंग अनुरोध सफलतापूर्वक भेजा गया!',
    bookingAccepted: 'बुकिंग स्वीकृत! श्रमिक आ रहा है।',
    bookingRejected: 'बुकिंग अस्वीकृत।',
    bookingCompleted: 'कार्य पूर्ण! कर्मचारी को रेटिंग दें।',
    errorOccurred: 'एक त्रुटि हुई। कृपया पुनः प्रयास करें।',
    posting: 'पोस्ट हो रहा...',
    submitting: 'जमा हो रहा...',
    required: 'कृपया सभी आवश्यक फ़ील्ड भरें',
    bid_amount: 'बिड राशि दर्ज करें',
    posted: 'जॉब पोस्ट हो गया!',
    bid_success: 'बिड सफलतापूर्वक लग गई!',
    lowest: 'सबसे कम बिड',
    close: 'बंद',
    be_first: 'पहली बिड करें!',
    no_bids_yet: 'अभी तक कोई बिड नहीं',
    login_required: 'जारी रखने के लिए लॉगिन करें',
  },
};

// ✅ নম্বর ট্রান্সলেট করার ফাংশন
export function translateNumber(num: string | number, lang: string): string {
  const numStr = num.toString();
  const digits: Record<string, Record<string, string>> = {
    en: { '0': '0', '1': '1', '2': '2', '3': '3', '4': '4', '5': '5', '6': '6', '7': '7', '8': '8', '9': '9' },
    bn: { '0': '০', '1': '১', '2': '২', '3': '৩', '4': '৪', '5': '৫', '6': '৬', '7': '৭', '8': '৮', '9': '৯' },
    ar: { '0': '٠', '1': '١', '2': '٢', '3': '٣', '4': '٤', '5': '٥', '6': '٦', '7': '٧', '8': '٨', '9': '٩' },
    hi: { '0': '०', '1': '१', '2': '२', '3': '३', '4': '४', '5': '५', '6': '६', '7': '७', '8': '८', '9': '९' },
  };
  
  return numStr.split('').map(char => digits[lang]?.[char] || char).join('');
}

// ✅ কারেন্সি ট্রান্সলেট করার ফাংশন
export function getCurrencySymbol(lang: string): string {
  const currencies: Record<string, string> = {
    en: 'QAR',
    bn: 'রিয়াল',
    ar: 'ريال',
    hi: 'रियाल',
  };
  return currencies[lang] || 'QAR';
}

export function getText(lang: LangCode, key: string): string {
  return texts[lang]?.[key] || texts.en[key] || key;
}
// lib/language.ts - নিচে এই ৩টি ফাংশন যোগ করুন (ফাইলের শেষে)

// ═══════════════════════════════════════════════════════════
// নাম ট্রান্সলেট (গ্লোবাল)
// ═══════════════════════════════════════════════════════════
export function translateName(name: string, lang: string): string {
  const nameTranslations: Record<string, Record<string, string>> = {
    'Rojjob': { en: 'Rojjob', bn: 'রোজজব', ar: 'روجوب', hi: 'रोजजॉब' },
    'মাহাবুল': { en: 'Mahabul', bn: 'মাহাবুল', ar: 'ماهبول', hi: 'माहाबुल' },
    'সুমন বিশ্বাস': { en: 'Suman Biswas', bn: 'সুমন বিশ্বাস', ar: 'سومان بيسواس', hi: 'सुमन बिस्वास' },
    'RubelRana': { en: 'Rubel Rana', bn: 'রুবেল রানা', ar: 'روبل رانا', hi: 'रूबेल राणा' },
    'house Driver': { en: 'House Driver', bn: 'হাউস ড্রাইভার', ar: 'سائق منزلي', hi: 'हाउस ड्राइवर' },
  };
  return nameTranslations[name]?.[lang] || name;
}

// ═══════════════════════════════════════════════════════════
// ক্যাটাগরি নাম ট্রান্সলেট (গ্লোবাল)
// ═══════════════════════════════════════════════════════════
export function translateCategory(category: string, lang: string): string {
  const categoryNames: Record<string, Record<string, string>> = {
    Driver: { en: 'Driver', ar: 'سائق', bn: 'ড্রাইভার', hi: 'ड्राइवर' },
    Electrician: { en: 'Electrician', ar: 'كهربائي', bn: 'ইলেকট্রিশিয়ান', hi: 'इलेक्ट्रीशियन' },
    Plumber: { en: 'Plumber', ar: 'سباك', bn: 'প্লাম্বার', hi: 'प्लंबर' },
    Mason: { en: 'Mason', ar: 'بناء', bn: 'রাজমিস্ত্রি', hi: 'राजमिस्त्री' },
    'AC Technician': { en: 'AC Technician', ar: 'فني تكييف', bn: 'এসি টেকনিশিয়ান', hi: 'एसी तकनीशियन' },
    Painter: { en: 'Painter', ar: 'دهان', bn: 'পেইন্টার', hi: 'पेंटर' },
    Carpenter: { en: 'Carpenter', ar: 'نجار', bn: 'কার্পেন্টার', hi: 'बढ़ई' },
    Welder: { en: 'Welder', ar: 'لحام', bn: 'ওয়েল্ডার', hi: 'वेल्डर' },
    Cleaner: { en: 'Cleaner', ar: 'منظف', bn: 'ক্লিনার', hi: 'क्लीनर' },
    Cook: { en: 'Cook', ar: 'طباخ', bn: 'রাঁধুনি', hi: 'रसोइया' },
    Helper: { en: 'Helper', ar: 'مساعد', bn: 'হেল্পার', hi: 'हेल्पर' },
    Gardener: { en: 'Gardener', ar: 'بستاني', bn: 'মালী', hi: 'माली' },
  };
  return categoryNames[category]?.[lang] || category;
}

// ═══════════════════════════════════════════════════════════
// জেন্ডার ট্রান্সলেট (গ্লোবাল)
// ═══════════════════════════════════════════════════════════
export function translateGender(gender: string, lang: string): string {
  const map: Record<string, Record<string, string>> = {
    male: { en: 'Male', bn: 'পুরুষ', ar: 'ذكر', hi: 'पुरुष' },
    female: { en: 'Female', bn: 'মহিলা', ar: 'أنثى', hi: 'महिला' },
    other: { en: 'Other', bn: 'অন্যান্য', ar: 'آخر', hi: 'अन्य' },
  };
  return map[gender]?.[lang] || gender;
}